### ISSUE TITLE
Fix duplicate bind message

### ISSUE THREAD

**Issue by ajivoin** [ajivoin/tug-of-war#27]

**Comment by sullyvannunes** [comment]
@ajivoin I couldn't reproduce the duplicate bind message but I could see an issue regarding an async request to Discord's channels API that I believe is related.  I would like to open a pull request to fix this issue

**Comment by ajivoin** [comment]
@sullyvannunes 
>  I couldn't reproduce the duplicate bind message but I could see an issue regarding an async request to Discord's channels API that I believe is related.

Go for it! I think that would fix it
